[project]
name = "ai-customer-insights-engine"
version = "0.1.0"
description = "RAG application for customer reviews analysis"
requires-python = ">=3.11"

dependencies = [
    "python-dotenv",
    "pandas",
    "langchain-core",
    "langchain-huggingface",
    "langchain-openai",
    "langchain-text-splitters",
    "langchain-chroma",
    "streamlit"
]

[tool.setuptools.packages.find]
where = ["."]